name: dart_emoji
description: "A light-weight Emoji ðŸ“¦ for Dart & Flutter with all up-to-date emojis written in pure Dart ðŸ˜„ . Made from ðŸ’¯% â˜• with â¤ï¸!"
version: 0.1.1+2
homepage: "https://github.com/GatchHQ/dart-emoji"

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.19.3
