name: dart_emoji
description: "ðŸ‘‰ A light-weight Emoji ðŸ“¦ for Flutter with all up-to-date emojis ðŸ˜„. Made from ðŸ’¯% â˜• with â¤ï¸!"
version: 2.2.1+1
homepage: "https://github.com/petehouston/flutter-emoji"

environment:
  sdk: ">=2.1.0 <3.0.0"

dev_dependencies:
  test: ^1.19.3

flutter: null
